# This is Foreman's configuration file. You can edit it to tell Foreman about
# new tools that you'd like to install, or to change versions of tools you
# already have.

# When adding new tools, make sure to run `foreman install` so that their
# binaries are installed.

[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.0.0-rc.3" }
selene = { source = "kampfkarren/selene", version = "0.14.0" }
stylua = { source = "johnnymorganz/stylua", version = "0.11.0" }
