name: build

on:
  push:
    tags:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Foreman Setup
      uses: Roblox/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # useful for debugging differences between CI and local environment
    - name: Debug Info
      shell: bash
      run: |
        foreman list

    - name: Build
      shell: bash
      run: |
        rojo build build.project.json --output SonarBrushtool.rbxm

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: SonarBrushtool.rbxm
